version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 62
        payload: AAAAPgADAAB1c2VyAHBvc3RncmVzAGRhdGFiYXNlAHBvc3RncmVzAGNsaWVudF9lbmNvZGluZwBVVEY4AAA=
    postgresResp:
        identfier: PostgresResponse
        length: 13
        payload: UgAAAAwAAAAFpAaURw==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 41
        payload: cAAAAChtZDViY2YxMjYyYmFhNDRlYTdlNjI1NTlmNjhmNDBlNzU4MAA=
    postgresResp:
        identfier: PostgresResponse
        length: 342
        payload: UgAAAAgAAAAAUwAAABZhcHBsaWNhdGlvbl9uYW1lAABTAAAAGWNsaWVudF9lbmNvZGluZwBVVEY4AFMAAAAXRGF0ZVN0eWxlAElTTywgTURZAFMAAAAZaW50ZWdlcl9kYXRldGltZXMAb24AUwAAABtJbnRlcnZhbFN0eWxlAHBvc3RncmVzAFMAAAAUaXNfc3VwZXJ1c2VyAG9uAFMAAAAZc2VydmVyX2VuY29kaW5nAFVURjgAUwAAADFzZXJ2ZXJfdmVyc2lvbgAxMC41IChEZWJpYW4gMTAuNS0yLnBnZGc5MCsxKQBTAAAAI3Nlc3Npb25fYXV0aG9yaXphdGlvbgBwb3N0Z3JlcwBTAAAAI3N0YW5kYXJkX2NvbmZvcm1pbmdfc3RyaW5ncwBvbgBTAAAAEVRpbWVab25lAFVUQwBLAAAADAAAACrFpK9dWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 55
        payload: UQAAADZTRUxFQ1QgMSBGUk9NIHBnX2RhdGFiYXNlIFdIRVJFIGRhdG5hbWU9J25vdGVzZGInAA==
    postgresResp:
        identfier: PostgresResponse
        length: 66
        payload: VAAAACEAAT9jb2x1bW4/AAAAAAAAAAAAABcABP////8AAEQAAAALAAEAAAABMUMAAAANU0VMRUNUIDEAWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 5
        payload: WAAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 0
        payload: ""
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 5
        payload: WAAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 0
        payload: ""
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 61
        payload: AAAAPQADAAB1c2VyAHBvc3RncmVzAGRhdGFiYXNlAG5vdGVzZGIAY2xpZW50X2VuY29kaW5nAFVURjgAAA==
    postgresResp:
        identfier: PostgresResponse
        length: 24
        payload: UgAAABcAAAAKU0NSQU0tU0hBLTI1NgAA
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 56
        payload: cAAAADdTQ1JBTS1TSEEtMjU2AAAAACFuLCxuPSoscj1HTWtOa2VBR2tXdEFiRzJ3K0VCQzc3NWw=
    postgresResp:
        identfier: PostgresResponse
        length: 93
        payload: UgAAAFwAAAALcj1HTWtOa2VBR2tXdEFiRzJ3K0VCQzc3NWw2WjhJTkEvMTBIWHMrRUh4YUhKT29nZGQscz02R0p1VlFTNWRURi9iNXhKOVptTVB3PT0saT00MDk2
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 109
        payload: cAAAAGxjPWJpd3Mscj1HTWtOa2VBR2tXdEFiRzJ3K0VCQzc3NWw2WjhJTkEvMTBIWHMrRUh4YUhKT29nZGQscD13L3JkNXFGY3Q2M0FpNDJuVzRGWXl2bVZvR29YcEhSWTd0T0I5M3FWMElBPQ==
    postgresResp:
        identfier: PostgresResponse
        length: 465
        payload: UgAAADYAAAAMdj1vaCt3NkNTaDlsVVFTMm9uU2RCTnB5cngwY0VFSjYrWjZvUCtlUzRpYXk0PVIAAAAIAAAAAFMAAAAWYXBwbGljYXRpb25fbmFtZQAAUwAAABljbGllbnRfZW5jb2RpbmcAVVRGOABTAAAAF0RhdGVTdHlsZQBJU08sIE1EWQBTAAAAJmRlZmF1bHRfdHJhbnNhY3Rpb25fcmVhZF9vbmx5AG9mZgBTAAAAF2luX2hvdF9zdGFuZGJ5AG9mZgBTAAAAGWludGVnZXJfZGF0ZXRpbWVzAG9uAFMAAAAbSW50ZXJ2YWxTdHlsZQBwb3N0Z3JlcwBTAAAAFGlzX3N1cGVydXNlcgBvbgBTAAAAGXNlcnZlcl9lbmNvZGluZwBVVEY4AFMAAAAyc2VydmVyX3ZlcnNpb24AMTUuNCAoRGViaWFuIDE1LjQtMS5wZ2RnMTIwKzEpAFMAAAAjc2Vzc2lvbl9hdXRob3JpemF0aW9uAHBvc3RncmVzAFMAAAAjc3RhbmRhcmRfY29uZm9ybWluZ19zdHJpbmdzAG9uAFMAAAAVVGltZVpvbmUARXRjL1VUQwBLAAAADAAAAFJh1TldWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 147
        payload: UAAAAEQASU5TRVJUIElOVE8gbm90ZXModGl0bGUsIGNvbnRlbnQpIFZBTFVFUygkMSwgJDIpIFJFVFVSTklORyAqAAAAQgAAADcAAAACAAAAAAACAAAACkZpcnN0IE5vdGUAAAAVVGhpcyBpcyBhIGZpcnN0IG5vdGUuAABEAAAABlAARQAAAAkAAAAAAFMAAAAE
    postgresResp:
        identfier: PostgresResponse
        length: 161
        payload: MQAAAAQyAAAABFQAAABNAANpZAAAAEAGAAEAAAAXAAT/////AAB0aXRsZQAAAEAGAAIAAAQT//8AAAEDAABjb250ZW50AAAAQAYAAwAAABn///////8AAEQAAAAyAAMAAAABMQAAAApGaXJzdCBOb3RlAAAAFVRoaXMgaXMgYSBmaXJzdCBub3RlLkMAAAAPSU5TRVJUIDAgMQBaAAAABUk=
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 25
        payload: UQAAABhTRUxFQ1QgKiBGUk9NIG5vdGVzAA==
    postgresResp:
        identfier: PostgresResponse
        length: 149
        payload: VAAAAE0AA2lkAAAAQAYAAQAAABcABP////8AAHRpdGxlAAAAQAYAAgAABBP//wAAAQMAAGNvbnRlbnQAAABABgADAAAAGf///////wAARAAAADIAAwAAAAExAAAACkZpcnN0IE5vdGUAAAAVVGhpcyBpcyBhIGZpcnN0IG5vdGUuQwAAAA1TRUxFQ1QgMQBaAAAABUk=
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 5
        payload: WAAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 0
        payload: ""
